### ISSUE TITLE
Problem Building Packages via "For Users" Instructions 

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/calamari#201]
I am currently evaluating Calamari in an enterprise environment and have been following the instructions given in this guide: http://calamari.readthedocs.org/en/latest/development/building_packages.html
Additionally, I have referenced this article: http://ceph.com/category/ceph-calamari/

I am running into a problem with salt-call in the VM, however. Running "vagrant ssh" and "sudo salt-call state.highstate" gives me the following error.

![Error](https://cloud.githubusercontent.com/assets/3989526/4533876/eebb3b88-4d9f-11e4-928c-a4252f25cbaa.png)

I am unsure how to get around this, as the VM is re-provisioned each time "vagrant up" is called. A common problem I face in development is that, being in an enterprise environment, I am behind a proxy. This is my first suspect on the issue, but I am unsure how to resolve.

**Comment by joehandzik** [comment]
Hi friends.

The deja-vu was pretty heavy in this thread, I ran into all the problems Blaine laid out (it's like we sit behind the same proxy or something...). After running into a set of problems with installing vagrant-proxyconf, I finally got to where Blaine was on this last post, and in an act of semi-desperation started looking for reasons why the script I'm looking at in this terminal screenshot would be broken. 
![urllib2_ftw](https://cloud.githubusercontent.com/assets/7061812/6696154/25ee01e6-ccb5-11e4-9e8f-38401baf7d95.PNG)

(the screenshot is actually of my suggested change...pretend like it still reads "urllib")

After some quality time with google, I found this page: https://docs.python.org/3/howto/urllib2.html

Near the bottom of the page, I found this tidbit: 

Note Currently urllib.request does not support fetching of https locations through a proxy.

So...I swapped the bootstrap_salt.sh script to use urllib2 instead of urllib...and everything appears to work fine! I executed the script and it successfully installed Salt. Would it be alright to change the urllib-boostrap-salt.sh script to use urllib2?

**Comment by dmick** [comment]
Sure!  It may also not be necessary anymore; it was a workaround for the upstream salt bootstrap relying on a later version of curl (again with https problems) that didn't exist on ... rhel6 maybe?...I may have left comments.  But maybe we don't need it at all these days?  That would be a better fix if possible

**Comment by joehandzik** [comment]
I'm up for either, just tell me which you prefer and we'll implement it. I think Blaine ended up working around his problems (that I didn't realize he worked around...) by hard-coding to curl.

**Comment by dmick** [comment]
If you could test without it (remove the line in Vagrantfile that requests it), on the older distros especially (at least rhel6), that would be awesome.
